### ISSUE TITLE
We are asking a region for a chunk out of bound

### ISSUE THREAD

**Issue by TheButterbrotMan** [Cristelknight999/Unstructured#2]
Minecraft: 1.18.2
Fabric: 0.14.8
https://bytebin.lucko.me/hgycWn1S24

Seems to be connected to Piglin/Hoglin spawning.

**Comment by BosterJowls** [comment]
Is there a recommended solution for this? I tried to use the config and disabled the piglin outpost completely, however, that didn't resolve the issue.

**Comment by TheButterbrotMan** [comment]
> Is there a recommended solution for this? I tried to use the config and disabled the piglin outpost completely, however, that didn't resolve the issue.

for me this also did not help

**Comment by TheButterbrotMan** [comment]
> > Is there a recommended solution for this? I tried to use the config and disabled the piglin outpost completely, however, that didn't resolve the issue.
> 
> for me this also did not help

sadly they dont wanna fix it :(

**Comment by Cristelknight** [comment]
I want to fix it. But idk what the problem is. I can’t get the bug. And I have no idea how and what to fix

**Comment by BosterJowls** [comment]
Upon further investigation (adding and removing mods one by one), I stopped getting the crash when I removed "So I heard you were talking crap bout minecraft's difficulty" mod

**Comment by BosterJowls** [comment]
So, turning off piglins spawn riding hoglins from the SIHYWTCAMD mod stopped the out of bounds error.

**Comment by TheButterbrotMan** [comment]
https://github.com/sf-inc/sihywtcamd/issues/36

**Comment by BosterJowls** [comment]
It is compatible, just turn off the piglins spawn riding hoglins.

**Comment by BosterJowls** [comment]
what is that?
