### ISSUE TITLE
[1.19.2] Crash on launch with the latest version of Forge

### ISSUE THREAD

**Issue by GoldenDarius** [Cristelknight999/Unstructured#4]
The game doesn't even load, as soon as I press the Play button and the launcher closes, Minecraft doesn't open at all and simply sends me back to the launcher, with no crash report or whatsoever. This only happens when this mod is installed

**Comment by Cristelknight** [comment]
That is really weird. Could you send the latest.log?

**Comment by GoldenDarius** [comment]
[2022-10-08-1.log](https://github.com/Cristelknight999/Unstructured/files/9740012/2022-10-08-1.log)
 Here it is, sorry for the late reply. I've tested it multiple times and I just fail to understand what is causing it

**Comment by Cristelknight** [comment]
It seems like it it really is a problem with unstructured. I‘ll try to fix it. But idk if I can fix it because I don’t have that problem

**Comment by GoldenDarius** [comment]
It could be incompatibility with some other structure mod I have installed, but I deem that as unlikely since it worked fine in 1.19, before I moved to 1.19.2

**Comment by Cristelknight** [comment]
i think i fixed it, could you test it new version on curseforge. (0.5.4)

**Comment by GoldenDarius** [comment]
Imma get to test it immediately

**Comment by GoldenDarius** [comment]
Yeah nope, it crashed still.
[latest.log](https://github.com/Cristelknight999/Unstructured/files/9747884/latest.log)

**Comment by ItzLucaGER** [comment]
Got the exact same issue.
Crashreport:
[crash-2022-10-08_17.39.52-fml.txt](https://github.com/Cristelknight999/Unstructured/files/9747913/crash-2022-10-08_17.39.52-fml.txt)

**Comment by GoldenDarius** [comment]
you're lucky it gives you a crash report, to me it does not

**Comment by GoldenDarius** [comment]
I have tried to only play in 1.19.2 Using Unstructured, and I still crahsed. 43.1.34 version of Forge is clearly causing something weird to the mod
[latest.log](https://github.com/Cristelknight999/Unstructured/files/9748620/latest.log)

**Comment by Cristelknight** [comment]
i think i fixed it, could you test it new version on curseforge. (0.5.5)

**Comment by GoldenDarius** [comment]
Sorry for the late response, I'll get to test it immediately

**Comment by GoldenDarius** [comment]
Everything seems to work as intended at last, thank you.
