### ISSUE TITLE
Forge 1.19.2 Crash on Startup

### ISSUE THREAD

**Issue by big-tdawg** [Cristelknight999/Unstructured#5]
I receive this crash everytime I try to launch my game with Unstructured installed. This happens on both versions of Unstructured for 1.19.2.

[latest.log](https://github.com/Cristelknight999/Unstructured/files/9748020/latest.log)

**Comment by OcrSu** [comment]
[debug.log](https://github.com/Cristelknight999/Unstructured/files/9781560/debug.log)
i have the same issue.

**Comment by Cristelknight** [comment]
Fixed in unstructured 0.5.5
